config/routes.rb
Rails.application.routes.draw do

  get 'administration/home'

  get 'administration/waiting_snippets'

  resources :bootstrapversions
  
  resources :snippets do
    member do
      get 'iframe'
      get 'user_status'
      get 'admin_status'
      get 'favorite'
      get 'fork_snippet'
    end
  end

  resources :tags
  
  devise_for :users
  
  resources :users do
    member do
      get 'profile'
    end
    
  end
  root to: 'snippets#index'
  get 'home/main'

end

app/models/snippet.rb
# == Schema Information
#
# Table name: snippets
#
#  id                  :integer          not null, primary key
#  title               :text
#  slug                :text
#  image_url           :text
#  original_url        :text
#  html_content        :text
#  html_code           :text
#  css_code            :text
#  js_code             :text
#  description         :text
#  user_id             :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  iframe_url_original :text
#  iframe_html_content :text
#  research_name       :text
#  token               :string
#  bootstrapversion_id :integer
#  views_count         :integer          default(0)
#  is_scraped          :boolean          default(FALSE)
#  approved            :boolean          default(FALSE)
#  refused             :boolean          default(FALSE)
#  send_for_approval   :boolean          default(FALSE)
#  comment_for_refusal :text
#  is_analysed         :boolean          default(FALSE)
#  status              :integer          default(0)
#  favorites_count     :integer          default(0), not null
#

class Snippet < ActiveRecord::Base
  ##-- Requirements and Concerns ---
  include CommonMethods
  include Taggable

  #extend FriendlyId
  #friendly_id :title, use: :slugged

  ##-- Constants--------------------

  ##-- Virtual Attributes ----------
  attr_writer :bootstrap_version

  ##-- Validations -----------------
  # validates :email, presence: true
  # validates :username, uniqueness: { case_sensitive: false }
  # validates_uniqueness_of :acronym, :allow_blank => true, :scope => [:group_id], :case_sensitive => false
  validates :title, presence: true
  validates :original_url, uniqueness: { :allow_blank => true, :scope => [:is_scraped] }

  #validates :original_url, presence: true
  #validates :original_url, uniqueness: true

  ##-- Callbacks -------------------
  after_save :update_research_name
  after_create :generate_random_token
  before_update  :save_bootstrap_version

  ##-- Associations ----------------
  # has_many :roles, dependent: :destroy
  # has_many :users, through: :memberships
  belongs_to :user
  belongs_to :bootstrapversion
  has_many :similar_snippets, through: :tags, :class_name => "Snippet", :source => :snippets

  has_many :favorites
  has_many :fans, through: :favorites, :class_name => "User", :source => :user
  ##-- Scopes ----------------------
  scope :approved, -> { where(status: 2) }
  scope :not_approved, -> { where(status: 2).not }
  scope :waiting, -> { where(status: 1) }
  
  ##-- Methods ---------------------
  # Easy method for pretty URLS
  def to_param
    return "#{id}-#{title}".parameterize
  end
  
  # Method that handles all the filtering of the params
  def self.filter(attributes)
    attributes.inject(self) do |scope, (key, value)|
      #return scope.scoped if value.blank?
      if value.blank?
        scope.all
      else
          case key.to_sym
          when :bootstrap_version
            bootstrap_version = Bootstrapversion.find_by(:name => "%#{value}%")
            scope.where("snippets.bootstrapversion_id = ?", bootstrap_version.id)
          when :search_name # regexp search
            scope.where('snippets.title ilike ? OR snippets.research_name ilike ?', "%#{value}%", "%#{value}%")
          when :starting_letter # regexp search
            letter = I18n.transliterate(value.to_s.strip.downcase).to_s
            puts letter
            scope.where('snippets.title ILIKE ? OR snippets.research_name ILIKE ?', "%#{letter}%", "%#{letter}%")
          when :status
            status = "#{value}".to_s.to_i
            scope.where(:status => status)
          when :order # order=field-(ASC|DESC)
            attribute, order = value.split("-") 
            scope.order("#{self.table_name}.#{attribute} #{order}")
          else # unknown key (do nothing or raise error, as you prefer to)
          scope.all
          end 
      end
    end
  end
  
  #Snippet.filter({:starting_letter => "image"})

  # Class method to create a new snippet from scratch. Pass the User etc...
  def self.create_new(user)
    snippet = self.new(:title => "New Snippet", :html_code => "<h3>Write the HTML code here</h3>")
    user.snippets << snippet
    Bootstrapversion.where('name = ?', "3.3.0").first.snippets << snippet
    return snippet
  end

  # Method to create a new snippet from a fork
  def create_fork_new(user)
    new_snippet = user.snippets.build(:title => "Fork of : " + self.title.to_s, :html_code => self.html_code, :css_code => self.css_code, :js_code => self.js_code, :bootstrapversion_id => self.bootstrapversion.id)
    new_snippet.save
    self.tags.each do |t|
      new_snippet.tags << t
    end
    return new_snippet
  end

  # Puts the snippet in the favorite of the user
  def favorite_from(user)
    if user.favorite_snippets.find_by(:id => self.id)
      self.fans.destroy(user)
      return "Snippet removed from your favorites"
    else
      self.fans << user
      return "Snippet now in favorites"
    end
  end

  def is_favorite(user)
    return !user.favorite_snippets.find_by(:id => self.id).nil?
  end

  # Defavorite the snippet from the user
  def defavorite_from(user)
    if user.favorite_snippets.find_by(:id => self.id)
      user.favorite_snippets.destroy(self)
      return "Snippet correctly removed from favorites"
    else
      return "Snippet not in favorites"
    end
  end

  ## STATUS RELATED METHODS
  # Status 0 nothing, 1 Waiting, 2 Approved, 3 Refused

  # Method that permits for the administrator to change the status of the snippet
  def admin_status_update(status)
    status = status.to_i
    if status == 2
      self.update_column(:status, 2)
      return "Accepted"
    elsif status == 3
      self.update_column(:status, 3)
      return "Refused"
    elsif status == 1
      self.update_column(:status, 1)
      return "Waiting"
    end
  end

  # Puts the snippet in the waiting
  def user_status_update(status)
    status = status.to_i
    if status == 0
      self.update_column(:status, 0)
      return "Hidden"
    elsif status == 1
      self.update_column(:status, 1)
      return "Waiting for approval"
    end
  end

  def human_status
    case self.status.to_i
    when 0
      return "Snippet Hidden"
    when 1
      return "Snippet Waiting for approval"
    when 2
      return "Snippet Approved"
    when 3
      return "Snippet Refused by administrators"
    else
    return "Unknown Status"
    end
  end

  # If the snippet needs to display a put in waiting area ?
  def need_waiting?
    if self.status == 0 || self.status == 3
    return true
    else
    return false
    end
  end

  ## END OF STATUS METHODS

  # Find the snippets that share the tags of the snippet
  def get_similar_snippets(number)
    return self.similar_snippets.approved.order('RANDOM()').first(number.to_i)
  end

  def bootstrap_version
    if @bootstrap_version
    return @bootstrap_version
    elsif self.bootstrapversion
    return self.bootstrapversion.name
    else
      return nil
    end
  end

  ### FOR PARSING ###

  # Convert the content in Nokogiri Nodes
  def html_content_to_html
    html = Nokogiri::HTML(self.html_content)
  end

  # Convert the content of the Iframe in Nokogiri Nodes
  def html_iframe_to_html
    html = Nokogiri::HTML(self.iframe_html_content)
  end

  def snippet_preview
    html = self.html_iframe_to_html
  end

  # Get the css code
  def get_css_code
    begin
      return self.snippet_preview.css('head style').first.text.strip
    rescue
      return ""
    end
  end

  # Update the CSS code in the field
  def update_css_code
    self.update_column(:css_code, self.get_css_code)
  end

  def get_js_code
    begin
      return  self.snippet_preview.css('body script').first.text.to_s.strip
    rescue
      return ""
    end
  end

  # Update the JS code in the field
  def update_js_code
    self.update_column(:js_code, self.get_js_code)
  end

  def get_html_code
    code = self.snippet_preview.css('body').first
    if code
      code.css('script').remove
    return code.inner_html.to_s.strip
    else
      return ""
    end
  end

  # Update the JS code in the field
  def update_html_code
    self.update_column(:html_code, self.get_html_code)
  end

  def get_raw_html_code
    code = self.snippet_preview.css('body').first.to_s
  end

  # Find the URL of the Iframe to have a clear Iframe Html Content
  def update_original_iframe_url
    begin
      iframe_url = self.html_content_to_html.css('iframe').first['src'].to_s
      self.update(:iframe_url_original => iframe_url)
    rescue
      puts "error in the update"
    end
  end

  def update_number_views
    begin
      text = self.html_content_to_html.css('#action-bar > a.btn.btn-default.disabled').text
      nb = text.strip.split(' ').first.gsub!('K', '').to_s.to_f
      nb = nb * 1000
      self.update_column(:views_count, nb.to_i)
    rescue
      puts "Error while updating the number of views"
    end
  end

  # Get the tags in the main page of the snippet
  def get_tags
    html = self.html_content_to_html
    array =[]
    tags = html.css('#tags a span')
    tags.each do |tag|
      puts tag
      array << tag.text
    end

    array.each do |t|
      sanitize_name = Tag.sanitize_name(t.to_s)
      tag = Tag.find_or_create_by(name: sanitize_name)
      begin
        self.tags << tag
      rescue
        puts "Already taken"
      end
    end
  end

  # Get the username and create the instance
  def update_username
    html = self.html_content_to_html
    username = html.css('.title-bar h4 a').first.text
    email = username + "@fakelouis.com"
    user = User.find_by(:pseudo => username)
    if user.nil?
      user = User.new(:pseudo => username, :email => email, :password => 'password123', :password_confirmation => 'password123', :is_real => false)
      user.save(:validate => false)
    end
    if user
    self.user = user
    self.save
    else

    end
  end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create, :user_status, :admin_status, :fork_snippet]
  before_action :set_snippet, only: [:show, :edit, :update, :destroy, :iframe, :user_status, :admin_status, :favorite, :fork_snippet]
  before_action :correct_user, only: [:edit, :update, :destroy, :user_status]
  before_action :is_administrator?, only: [:admin_status]
  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.approved.includes(:tags).paginate(:page => params[:page], :per_page => 20)

    letter = params[:starting_letter]
    if !letter.nil?
      #@letter = I18n.transliterate(letter.to_s.strip.downcase).to_s
      #@snippets = Snippet.approved.where('snippets.title ilike ? OR snippets.research_name ilike ?', "%#{@letter}%", "%#{@letter}%").includes(:tags).paginate(:page => params[:page], :per_page => 20)
      @snippets = Snippet.approved.filter(params).includes(:tags).paginate(:page => params[:page], :per_page => 20)
    else
      @snippets = Snippet.approved.includes(:tags).paginate(:page => params[:page], :per_page => 20)
    end
    
    respond_to do |format|
      format.html
      format.js { render "/snippets/insert_snippets" }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    @tags = @snippet.tags
    # Increment the counter of the ciews for the snippet
    @snippet.increment!(:views_count)
  end

  def iframe
    render :layout => false
  end

  # This action is a redirection after creating a new instance in the DB
  def new
    @snippet = Snippet.create_new(current_user)
    redirect_to edit_snippet_path(@snippet)
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        @success = true
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      format.js
      else
        @success = false
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      format.js
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to profile_user_path(current_user), notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_status
    status = params[:status].to_s.to_i
    current_status = @snippet.user_status_update(status)
    respond_to do |format|
      @message = "The Status of the Snippet has now changed to " + current_status
      format.js { render "/layouts/message" }
    end
  end
  
  # Route to put the snippet in the favorite of the user
  def favorite
    if signed_in?
      message = @snippet.favorite_from(current_user)
      redirect_to @snippet, notice: message.to_s
      return
    else
      redirect_to @snippet, notice: "You must be logged in to perform this action"
      return
    end
  end
  
  # Create a new Snippet from a fork and redirect to the newly created one
  def fork_snippet
    new_snippet = @snippet.create_fork_new(current_user)
    redirect_to edit_snippet_path(new_snippet), notice: "Your new Snippet from the fork"
  end

  def admin_status
    status = params[:status].to_s.to_i
    message = @snippet.admin_status_update(status)
    respond_to do |format|
      format.html {redirect_to @snippet, notice: "The status is now : " + message.to_s }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_snippet
    @snippet = Snippet.find(params[:id])
  end

  # Check if this is the good user
  def correct_user
    if current_user.nil?
      redirect_to new_user_session_path, notice: 'You must be log in to perform this action'
    return
    else
      if @snippet.user == current_user || current_user.is_administrator
      return
      else
        redirect_to snippets_url,  notice: 'Not authorized to perform this action'
      return
      end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def snippet_params
    params.require(:snippet).permit(:bootstrap_version, :tags_list, :title, :slug, :image_url, :original_url, :html_content, :html_code, :css_code, :js_code, :description, :user_id)
  end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/edit.html.erb
<% provide(:title, "Editing " + @snippet.title) %>
<% provide(:description, "Editing a snippet" ) %>
<% provide(:keywords, "create snippets, bootstrap, html snippets, css code, javascript, developers")%>

<div class="row">

	<div class="col-sm-3 col-md-2 sidebar">
		<h4 class="text-center">Bootstrap</h4>
		<div class="col-md-12">
			<%= select('snippet', 'bootstrap_version', Bootstrapversion.all.collect {|b| [ b.bootstrap_name, b.name ] }, {include_blank: 'None', selected: @snippet.bootstrapversion.name}, class: "form-control")%>

		</div>
		
		
		<%= form_for(@snippet) do |f| %>
		<div class="form-group">
			<h4 class="text-center">Tags</h4>
			<%= f.text_field :tags_list, class: "form-control", :id => "taginput" %>
		</div>
		<% end %>

		<h3 class="text-center">Actions</h3>

		<div class="col-md-12 text-center">
			<div class="btn-group-vertical" role="group" aria-label="..." >

				<a href="#" type="button" id="save-snippet" class="btn btn-primary align-left" style="text-align: left;"><i class="fa fa-floppy-o"></i> Save snippet</a>
				<%= link_to iframe_snippet_path(@snippet), class: "btn btn-default align-left", style:"text-align: left;", type: "button", target: "_blank" do %>
				<i class="fa fa-desktop"></i> Full Screen
				<% end %>
				<%= link_to @snippet, class: "btn btn-warning", type: "button", target: "_blank" do  %>
				<i class="fa fa-eye"></i> See Snippet</span>
				<% end %>
				
				
				<%= link_to fork_snippet_snippet_path(@snippet), class: "btn btn-info", type: "button" do  %>
				<i class="fa fa-retweet"></i> Fork Snippet</span>
				<% end %>
				<%= link_to  @snippet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", style:"text-align: left;", type: "button" do %>
				<i class="fa fa-trash"></i> Destroy
				<% end %>
			</div>
		</div>
		
		

		<div class="col-md-12  well">
			<b>Status</b>: <%= @snippet.human_status%>
		</div>

		<% if @snippet.need_waiting? %>
		<div class="col-md-12 text-center">

			<%= link_to user_status_snippet_path(@snippet, :status => 1), remote: true, class: "btn btn-info" do %>
			<i class="fa fa-time"></i> Send for approval
			<% end %>

		</div>
		<% end %>
	</div>

	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

		<h1 class="page-header text-center tooltip-tag" title="Click to modify the title of the Snippet" id="snippet-name"><%= best_in_place @snippet, :title %></h1>

		<div class="col-sm-10 col-sm-offset-1 text-center">
			<div id="nav-widget" class="btn-group btn-group-justified">
				<div class="btn-group">
					<button type="button" class="btn text-uppercase" href="#preview" aria-controls="preview" role="tab" data-toggle="tab" id="show-preview">
						<i class="fa fa-map-marker fa-2x"></i> Preview</span>
					</button>
				</div>
				<div class="btn-group">
					<button type="button" class="btn text-uppercase" href="#html-code" aria-controls="html-code" role="tab" data-toggle="tab" id="show-html">
						<i class="fa fa-code fa-2x"></i> HTML
					</button>
				</div>
				<div class="btn-group">
					<button type="button" class="btn text-uppercase" href="#css-code" aria-controls="css-code" role="tab" data-toggle="tab" id="show-css">
						<i class="fa fa-code fa-2x"></i> CSS
					</button>
				</div>
				<div class="btn-group">
					<button type="button" class="btn text-uppercase" href="#js-code" aria-controls="js-code" role="tab" data-toggle="tab" id="show-js">
						<i class="fa fa-code fa-2x"></i> JS
					</button>
				</div>
			</div>
		</div>

		<div role="tabpanel" class="col-sm-12">

			<!-- Nav tabs -->

			<!-- Tab panes -->
			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="preview">
					<div id="playground-container">
						<div id="preview-container" >
							<iframe id="snippet-preview" class="preview-iframe" height="496" src="<%= iframe_snippet_path(@snippet) %>"></iframe>
						</div>
					</div>
				</div>
				<div role="tabpanel" class="tab-pane" id="html-code">

					<div>

						<div id="editor-html" class="ace-editor-class"><%= @snippet.html_code%></div>
					</div>
				</div>
				<div role="tabpanel" class="tab-pane" id="css-code">
					<div>

						<div id="editor-css" class="ace-editor-class"><%= @snippet.css_code%></div>
					</div>
				</div>
				<div role="tabpanel" class="tab-pane" id="js-code">
					<div>
						<div id="editor-js" class="ace-editor-class"><%= @snippet.js_code%></div>
					</div>

				</div>
			</div>

		</div>

		<div class="col-md-12">
			<hr />
			<div class="alert alert-warning">
				<i class="fa fa-warning"></i> If you want to provide information about how to use or customize your snippet, integrate it in the HTML code to display it on the preview
			</div>
		</div>

	</div>

</div>
<!-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.1.8/ace.js" type="text/javascript" charset="utf-8"></script>
<-->



<script>
		(function($) {

	$('.best_in_place').best_in_place();
	var snippetSaved = false;
	var htmleditor = ace.edit("editor-html");
	var jseditor = ace.edit("editor-js");
	var csseditor = ace.edit("editor-css");
	var version = '3.3.0';
	var snippetTitle = $('#snippet-name');

	// If it changes the bootstrap version come back to the preview
	$('select[name="snippet[bootstrap_version]"]').change(function(e){
	version = $(this).val();
	$('#show-preview').click();
	});

	function setEditorOptions(editor, type){
	editor.setTheme("ace/theme/clouds");
	editor.setHighlightActiveLine(false);
	editor.getSession().setMode("ace/mode/"+type);
	editor.commands.addCommand({
	name: 'save',
	bindKey: {win: 'Ctrl-S',  mac: 'Command-S'},
	exec: function(editor) {
	$('#save-snippet').click();
	},
	readOnly: false
	});
	editor.commands.addCommand({
	name: 'evaluate',
	bindKey: {win: 'Ctrl-Return',  mac: 'Command-Return'},
	exec: function(editor) {
	$('#show-preview').click();
	},
	readOnly: true
	});
	};

	setEditorOptions(htmleditor,'html');
	setEditorOptions(jseditor,'javascript');
	setEditorOptions(csseditor,'css');

	$('#show-html').click(function(e){
	e.preventDefault();
	markActive(this);
	//$('#editor-html').show().siblings().hide();
	//$('#preview-container').hide();
	htmleditor.resize();
	htmleditor.focus();
	});

	$('#show-js').click(function(e){
	e.preventDefault();
	markActive(this);
	//$('#editor-js').show().siblings().hide();
	//$('#preview-container').hide();

	jseditor.resize();
	jseditor.focus();
	});

	$('#show-css').click(function(e){
	e.preventDefault();
	markActive(this);
	//$('#editor-css').show().siblings().hide();
	//$('#preview-container').hide();

	csseditor.resize();
	csseditor.focus();
	});

	$('#save-snippet').click(function(e){
	e.preventDefault();
	//var l = Ladda.create(this);
	//l.start();
	$.ajax({
	type: 'PUT',
	url:  "<%= j snippet_path(@snippet) %>",
		data: { "snippet": { "html_code": htmleditor.getValue(),
		"css_code": csseditor.getValue(),
		"js_code": jseditor.getValue(),
		"tags_list": $('#taginput').val(),
		"title" : $('input[name="title"]').val(),
		"bootstrap_version" : version
		}},
		dataType: "script",
		success: function(data) {
		//console.log(data);
		}
		})
		});

		$('#show-preview').click(function(e){
		e.preventDefault();
		markActive(this);

		$('.playground-editor').hide();

		var html = buildSource(htmleditor, jseditor, csseditor);
		var iframe = document.createElement('iframe');

		iframe.src = 'about:blank';
		iframe.frameBorder="0";
		iframe.height = 496;
		iframe.className = 'preview-iframe';

		$('.preview-iframe').remove();
		$('div#preview-container').append(iframe);

		iframe.contentWindow.document.open('text/html', 'replace');
		iframe.contentWindow.document.write(html);
		iframe.contentWindow.document.close();

		$('#preview-container').show();
		});

		function markActive(el)
		{
		$('#nav-widget .btn-group button').removeClass('active');
		$(el).addClass('active');
		}
		var cssurls = {};
		var jsurls = {};

		cssurls['3.3.0'] = '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css';
		jsurls['3.3.0'] = '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js';
		cssurls['3.2.0'] = '//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css';
		jsurls['3.2.0'] = '//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js';
		cssurls['3.1.0'] = '//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css';
		jsurls['3.1.0'] = '//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js';
		cssurls['3.0.3'] = '//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css';
		jsurls['3.0.3'] = '//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js';
		cssurls['3.0.1'] = '//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css';
		jsurls['3.0.1'] = '//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js';
		cssurls['3.0.0'] = '//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css';
		jsurls['3.0.0'] = '//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js';
		cssurls['2.3.2'] = '//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css';
		jsurls['2.3.2'] = '//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js';

		function buildSource(htmleditor, jseditor, csseditor)
		{
		var code = {};
		code.html = htmleditor.getValue();
		code.css = csseditor.getValue();
		code.js = jseditor.getValue();
		code.bootstrapcss = cssurls[version];
		code.bootstrapjs = jsurls[version];

		var template = "<!doctype html>\n\
		<html>\n\
		<head>\n\
		<meta charset='utf-8'>\n\
		<meta name='viewport' content='width=device-width, initial-scale=1'>\n\
		<title>Snippet - Bootsnipp.com</title>\n\
		<link href='|bootstrapcss|' rel='stylesheet'>\n\
		<style>|css|\x3C/style>\n\
		\x3Cscript type='text/javascript' src='//code.jquery.com/jquery-1.10.2.min.js'>\x3C/script>\n\
		\x3Cscript type='text/javascript' src='|bootstrapjs|'>\x3C/script>\n\
		\x3Cscript type='text/javascript'>|js|\x3C/script>\n\
		</head>\n\
		<body>\n\
		|html|\n\
		</body>\n\
		</html>";

		content = template.replace(/\|(\w+)\|/g, function(match, str)
		{
		if(str in code) return code[str];
		return '';
		});

		return content;
		}

		var submitsnippet   = $('#submitsnippet');
		var thankyou        = $('#thankyou');
		var errorlist       = $('#error-list');
		var hideable        = $('.hideable');
		thankyou.hide();
		submitsnippet.submit(function(e){
		e.preventDefault();
		if(snippetSaved){
		submitsnippet.spin();
		$.ajax({
		url: 'http://bootsnipp.com/api/snippets',
		type: 'POST',
		dataType: 'json',
		data: $('form#submitsnippet').serialize(),
		success: function(data) {
		submitsnippet.spin(false);
		hideable.fadeOut();
		thankyou.fadeIn('slow');
		},
		error: function (xhr, ajaxOptions, thrownError) {
		submitsnippet.spin(false);
		alert('Error submitting snippet, please try again!');
		}
		});
		} else {
		alert('Please save the snippet first');
		}
		return false;
		});
		})(jQuery);
</script>

app/views/snippets/index.js.erb
$(function() {
	$("#insert-snippets").html("<%= escape_javascript render(partial: 'snippets_list', locals:{snippets: @snippets})%>");
	$('.paginations a').click(function() {
			$("#insert-snippets").html('<div class="text-center"><%= j image_tag "loading-glasses.gif"%></div>');
			$.get(this.href, null, null, 'html');
			return false;
		});
}); 

app/views/snippets/new.html.erb
<% provide(:title, "TITLE") %>
<% provide(:description, "Description" ) %>
<% provide(:keywords, "keyword1, keyword2")%>

<h1 class="page-header text-center">New Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Back', snippets_path, :class => "btn btn-warning" %>