config/routes.rb
Rails.application.routes.draw do

  get 'administration/home'

  get 'administration/waiting_snippets'

  resources :bootstrapversions
  
  resources :snippets do
    member do
      get 'iframe'
      get 'user_status'
      get 'admin_status'
      get 'favorite'
      get 'fork_snippet'
    end
  end

  resources :tags
  
  devise_for :users
  
  resources :users do
    member do
      get 'profile'
    end
    
  end
  root to: 'snippets#index'
  get 'home/main'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime
#  updated_at             :datetime
#  pseudo                 :string
#  is_administrator       :boolean          default(FALSE)
#  is_real                :boolean          default(TRUE)
#  slug                   :string
#

class User < ActiveRecord::Base
  ##-- Requirements and Concerns ---
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  include CommonMethods
  extend FriendlyId
  friendly_id :pseudo, use: :slugged
  ##-- Constants--------------------

  ##-- Virtual Attributes ----------

  ##-- Validations -----------------
  # validates :email, presence: true
  # validates :username, uniqueness: { case_sensitive: false }
  validates :pseudo, presence:true
  validates :pseudo, uniqueness: { case_sensitive: false }

  ##-- Callbacks -------------------

  ##-- Associations ----------------
  # has_many :roles, dependent: :destroy
  # has_many :users, through: :memberships
  has_many :snippets
  
  has_many :favorites
  has_many :favorite_snippets, through: :favorites, :class_name => "Snippet", :source => :snippet

  ##-- Scopes ----------------------
  # scope :active, -> { where(active: true) }

  ##-- Methods ---------------------
  
  # Find the admin and updates the status
  def self.define_administrator
    admin = self.find_by(:email => "louis.fourrier@gmail.com")
    admin.update(:is_administrator => true)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :profile]
  before_action :correct_user, except: [:show]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @snippets = @user.snippets.approved.paginate(:page => params[:page], :per_page => 20)
  end
  
  # Profile page of the user with the snippets
  def profile
    @snippets = @user.snippets.paginate(:page => params[:page], :per_page => 20)
    @favorite_snippets = @user.favorite_snippets.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end
    
    def correct_user
      if signed_in?
        if current_user == @user || is_administrator
          return
        else
          redirect_to root_path, notice: "You are not allowed to access this page"
          return
        end
      else
        redirect_to new_user_session_path, notice: 'You must be log in to perform this action'
        return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions text-center">
  	<% if user.new_record? %>
    <%= f.submit "Create", :class => "btn btn-success btn-lg" %>
    <% else %>
    <%= f.submit "Update", :class => "btn btn-success btn-lg" %>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "TITLE") %>
<% provide(:description, "Description" ) %>
<% provide(:keywords, "keyword1, keyword2")%>

<h1 class="page-header text-center">Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, :class => "btn btn-warning" %> |
<%= link_to 'Back', users_path, :class => "btn btn-info" %>

app/views/users/index.html.erb
<% provide(:title, "TITLE") %>
<% provide(:description, "Description" ) %>
<% provide(:keywords, "keyword1, keyword2")%>

<h1 class="page-header text-center">Users</h1>
<ul class="nav nav-pills nav-stacked tag-list">
	<% @users.each do |user| %>
		<li class="col-md-4 col-sm-6 col-xs-12 col-lg-3 ">
			<%= link_to user do %>
			<span class="badge pull-right"><%= user.snippets.count %></span>
			<%= user.pseudo %>
			<%end %>
		</li>
	<% end %>
</ul>


<br>

<%= link_to 'New User', new_user_path, :class => "btn btn-success" %>

app/views/users/new.html.erb
<% provide(:title, "TITLE") %>
<% provide(:description, "Description" ) %>
<% provide(:keywords, "keyword1, keyword2")%>

<h1 class="page-header text-center">New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, :class => "btn btn-warning" %>

app/views/users/profile.html.erb
<% provide(:title, "Profile of " + @user.pseudo) %>
<% provide(:description, "Administration page of the user " + @user.pseudo ) %>
<% provide(:keywords, "keyword1, keyword2")%>

<div class="col-md-12">
	<h1 class="page-header text-center"><%= @user.pseudo %> profile (<%= @user.snippets.count%> snippets)</h1>
</div>


<div class="col-md-12 text-center">
	<%= link_to edit_user_registration_path(@user), class: "btn btn-default" do  %>
	<i class="fa fa-cog"></i> Configure your account
	<% end %>
	<%= link_to new_snippet_path, class: "btn btn-info" do%>
	<i class="fa fa-plus"></i> New Snippet
	<% end%>
    <% link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>


<div id="insert-snippets" class="col-md-12">
	<%= render partial: "snippets/snippets_list", locals: {snippets: @snippets, edit_mode: true} %>
</div>

<div class="col-md-12">
	<h3 class="text-center">Favorites</h3>
	<%= render partial: "snippets/snippets_list", locals: {snippets: @favorite_snippets} %>
</div>

app/views/users/show.html.erb
<% provide(:title, "TITLE") %>
<% provide(:description, "Description" ) %>
<% provide(:keywords, "keyword1, keyword2")%>

<div class="col-md-12">
	<h1 class="page-header text-center">Snippets made by <%= link_to @user.pseudo, @user %> (<%= @user.snippets.count%>)</h1>
</div>
<div id="insert-snippets" class="col-md-12">
	<%= render partial: "snippets/snippets_list", locals: {snippets: @snippets} %>
</div>


<div class="col-md-12">
	<h2 class="text-center">Comments</h3> <div id="disqus_thread"></div>
	<script type="text/javascript">
		/* * * CONFIGURATION VARIABLES * * */
		var disqus_shortname = 'bootstrapsnippets';

		/* * * DON'T EDIT BELOW THIS LINE * * */
		(function() {
			var dsq = document.createElement('script');
			dsq.type = 'text/javascript';
			dsq.async = true;
			dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
			(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		})();
	</script>
	<noscript>
		Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
	</noscript>
</div>
<% if current_user and current_user.is_administrator %>
<div class="col-md-12">
	<%= link_to 'Edit', edit_user_path(@user) %>
    <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

<%= link_to 'Edit', edit_user_path(@user), :class => "btn btn-warning"  %> |
<%= link_to 'Back', users_path, :class => "btn btn-primary"  %>

<% end %>

app/views/users/show.js.erb
$(function() {
	$("#insert-snippets").html("<%= escape_javascript render(partial: 'snippets/snippets_list', locals:{snippets: @snippets})%>");
}); 