config/routes.rb
Rails.application.routes.draw do

  get 'administration/home'

  get 'administration/waiting_snippets'

  resources :bootstrapversions
  
  resources :snippets do
    member do
      get 'iframe'
      get 'user_status'
      get 'admin_status'
      get 'favorite'
      get 'fork_snippet'
    end
  end

  resources :tags
  
  devise_for :users
  
  resources :users do
    member do
      get 'profile'
    end
    
  end
  root to: 'snippets#index'
  get 'home/main'

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id             :integer          not null, primary key
#  name           :string
#  image_url      :text
#  first_letter   :string
#  research_name  :string
#  slug           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  snippets_count :integer
#  is_bootstrap   :boolean          default(FALSE)
#  taggings_count :integer          default(0), not null
#

class Tag < ActiveRecord::Base
  include CommonMethods
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  #mount_uploader :image_url, ImageUrlUploader
  
  validates :name, presence: true, uniqueness: true
  validates :name, length: { in: 2..30 } 
  
  before_validation :sanitize_name
  
  after_create :update_research_name
  after_create :update_first_letter
  
  has_many :taggings, dependent: :destroy
  has_many :snippets, :through => :taggings, source: :taggable, source_type: "Snippet"
  
  # Basic sanitize
  def sanitize_name
    self.name = Tag.sanitize_name(self.name)
  end
  
  # Class method to sanitier the name
  # TODO Problem is to check the name before create
  def self.sanitize_name(name)
    return name.to_s.strip.downcase
  end
  
  # Method for researrch name in common methods
  def title 
    self.name
  end 
  
  # Check the counters for taggings
  def self.check_taggings_count
    self.find_each { |tag| Tag.reset_counters(tag.id, :taggings) }
  end

  
  # Distinguish tags from the bootstrap version of the snippets
  def update_bootstrap_version
    names = Bootstrapversion.name_list
    if names.include?(self.name)
      self.update_column(:is_bootstrap, true)
    end
  end
  
  # Update the snippets counter
  def update_snippets_count
    self.update(:snippets_count => self.snippets.count)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :is_administrator?, except: [:show, :index]
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.where("tags.name ILIKE ?", "%#{params[:term]}%").order('tags.snippets_count DESC')
     respond_to do |format|
      format.html
      format.json { render :json => @tags.pluck(:name) }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @snippets = @tag.snippets.approved.filter(params).includes(:tags).paginate(:page => params[:page], :per_page => 20)
    respond_to do |format|
      format.html
      format.js { render "/snippets/insert_snippets" }
    end
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :image_url, :first_letter, :research_name, :slug)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_area :image_url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :first_letter %><br>
    <%= f.text_field :first_letter, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :research_name %><br>
    <%= f.text_field :research_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :slug %><br>
    <%= f.text_field :slug, :class => "form-control" %>
  </div>
  <div class="actions text-center">
  	<% if tag.new_record? %>
    <%= f.submit "Create", :class => "btn btn-success btn-lg" %>
    <% else %>
    <%= f.submit "Update", :class => "btn btn-success btn-lg" %>
    <% end %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<% provide(:title, "TITLE") %>
<% provide(:description, "Description" ) %>
<% provide(:keywords, "keyword1, keyword2")%>

<h1 class="page-header text-center">Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag, :class => "btn btn-warning" %> |
<%= link_to 'Back', tags_path, :class => "btn btn-info" %>

app/views/tags/index.html.erb
<% provide(:title, "Boostrap Snippets by Tags") %>
<% provide(:description, "All the tags associated with Bootstrap snippets of code" ) %>
<% provide(:keywords, "tags, Snippets of code, HTML, JS, CSS, Snippets, Bootstrap, Developers, Development")%>

<h1 class="page-header text-center">Snippets by Tags <small> Select a Tag</small></h1>


<ul class="nav nav-pills nav-stacked tag-list">
	<% @tags.each do |tag| %>
		<li class="col-md-4 col-sm-6 col-xs-12 col-lg-3 ">
			<%= link_to tag do %>
			<span class="badge pull-right"><%= tag.taggings.size %></span>
			<%= tag.name %>
			<%end %>
		</li>
	<% end %>
</ul>
<% if is_administrator %>
<%= link_to 'New Tag', new_tag_path, :class => "btn btn-success" %>
<% end %>

app/views/tags/new.html.erb
<% provide(:title, "TITLE") %>
<% provide(:description, "Description" ) %>
<% provide(:keywords, "keyword1, keyword2")%>

<h1 class="page-header text-center">New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path, :class => "btn btn-warning" %>

app/views/tags/show.html.erb
<% provide(:title, "Snippets of codes tagged with " + @tag.name) %>
<% provide(:description, "All the bootstrap snippets tagged with " + @tag.name ) %>
<% provide(:keywords, "Bootstrap, snippets, code , development, Snippets, HTML, JS, CSS, " + @tag.name)%>

<h1 class="text-center">Snippets tagged with #<%= link_to @tag.name, @tag %> (<%= @tag.snippets.count %>)</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<input id="firstletters" type="text" name="firstletter" class="form-control search-input" autofocus="autofocus" placeholder="Search a snippet" value="<%= params[:starting_letter] %>" />
	</div>
</div>

<div id="insert-snippets" class="col-md-12">
	<%= render partial: "snippets/snippets_list", locals: {snippets: @snippets} %>
</div>

<% if is_administrator %>
<%= link_to 'Edit', edit_tag_path(@tag), :class => "btn btn-warning"  %>
<% end %>

<div class="text-center">
	<%= link_to '<- Back to all tags', tags_path, :class => "btn btn-primary"  %>
</div>


<script>
	$(function() {
	var timeout;
	$("#firstletters").on('input',function(e){
	window.clearTimeout(timeout);
	timeout = window.setTimeout(function(){
		$("#insert-snippets").html('<div class="text-center"><%= j image_tag "loading-glasses.gif"%></div>');
			var letters = $("#firstletters").val();
			$.ajax({
				url : "",
				type : "GET",
				dataType: "script",
				data : {
				starting_letter : letters
				}
			})
	},500);
	})
	});
</script>

app/views/tags/show.js.erb
$(function() {
	$("#insert-snippets").html("<%= escape_javascript render(partial: 'snippets/snippets_list', locals:{snippets: @snippets})%>");
}); 