config/routes.rb
Rails.application.routes.draw do

  get 'administration/home'

  get 'administration/waiting_snippets'

  resources :bootstrapversions
  
  resources :snippets do
    member do
      get 'iframe'
      get 'user_status'
      get 'admin_status'
      get 'favorite'
      get 'fork_snippet'
    end
  end

  resources :tags
  
  devise_for :users
  
  resources :users do
    member do
      get 'profile'
    end
    
  end
  root to: 'snippets#index'
  get 'home/main'

end

app/views/layouts/_alert_message.js.erb
// Partial for alert message in javascript.

$(function () {
<% if local_assigns.has_key? :color_class %>
<% if color_class == "success"%>
toastr.success('<%= message %>');
<% elsif color_class == "error"%>
toastr.error('<%= message %>');
<% else%>
toastr.warning('<%= message %>');
<% end %>
<% else %>
toastr.warning('<%= message %>');
<% end %>
});

app/views/layouts/_end_scripts.html.erb
<%= yield(:end_script) %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container-fluid">
		<p class="text-muted">
			Nadvence Gadgets
		</p>
	</div>
</div>

app/views/layouts/_meta_common.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Bootstrap Snippets" %></title>
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PUT YOUR DESCRIPTION HERE" %>">
<%= favicon_link_tag 'favicon.ico' %>

<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="Bootstrap Snippets">
<meta itemprop="description" content="Bootstrap Snippets">
<meta name="keywords" lang="en" content="Bootstrap, Snippets">
<meta itemprop="image" content="http://www.nadvence-beta.com/assets/nadvence-share.png">

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@rebble_it">
<meta name="twitter:title" content="Bootstrap Snippets">
<meta name="twitter:description" content="Bootstrap Snippets">
<meta name="twitter:image" content="http://www.nadvence-beta.com/assets/nadvence-share.png">
<meta name="twitter:domain" content="">/>

<!-- Open Graph data -->
<meta property="og:title" content="Bootstrap Snippets" />
<meta property="og:type" content="website" />
<meta property="og:url" content="Bootstrap Snippets"/>
<meta property="og:image" content="http://www.nadvence-beta.com/assets/nadvence-share.png" />
<meta property="og:description" content="Bootstrap Snippets" />
<meta property="og:site_name" content="Bootstrap Snippets" />

<!-- Google plus author -->
<link rel="publisher" href="https://plus.google.com/+RebbleIt"/>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-nadvence" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				
			</button>
			<a class="navbar-brand" href="<%= root_path %>">Bootstrap snippets</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
			<ul class="nav navbar-nav">
				<li class="nadvence-family">
					<%= link_to "Snippets", snippets_path%>
				</li>
				<li class="nadvence-family">
					<%= link_to "Tags", tags_path%>
				</li>

				<% if current_user %>
				<li class="nadvence-family">
					<%= link_to "Your profile", profile_user_path(current_user) %></a>
				</li>
				<% end %>
				
				<% if is_administrator %>
				<li class="nadvence-family">
					<%= link_to "Administration", administration_home_path %></a>
				</li>
				<% end %>

			</ul>

			<% if current_user %>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span class="glyphicon glyphicon-user"></span>  <strong><%= current_user.pseudo %></strong> <span class="glyphicon glyphicon-chevron-down"></span> </a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "Settings", edit_registration_path(current_user) %>
						</li>
						<li>
							<%= link_to "New Snippet", new_snippet_path%>
						</li>
						<li>
							<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
						</li>
					</ul>
				</li>
			</ul>

			<% else %>

			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= link_to "Register", new_user_registration_path %>
				</li>
				<li>
					<%= link_to "Login", new_user_session_path %>
				</li>

			</ul>

			<% end %>

		</div><!--/.nav-collapse -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html itemscope itemtype="http://schema.org/WebPage">
	<head>
		<%= render partial: 'layouts/meta_common' %>
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application'%>
		<%= csrf_meta_tags %>
	</head>
	<body>
		
		<%= render partial: 'layouts/navbar' %>
		
		<div class="container-fluid main-container">
			<div class="row">
				<div class="col-md-12">
					<a href="javascript:" id="return-to-top" title="Return to top button"><i class="fa fa-arrow-up"></i></a>
					<div class="container">
						<% flash.each do |key, value| %>
						<div class="alert alert-warning text-center">
							<strong><%= value %></strong>
						</div>
						<% end %>
						
					</div>
					<%= yield %>
				</div>
			</div>
		</div>
		
		<div class="modal fade" id="layout-modal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">
							x
						</button>
						<h4 class="modal-title green"></h4>
					</div>
					<div class="modal-body"></div>
					<div class="modal-footer">
						<button class="btn btn-danger" data-dismiss="modal">
							<%= t('modal_close') %>
						</button>
					</div>
				</div>
			</div>
		</div>
		
		
		
		<%= render partial: 'layouts/end_scripts' %>
		
	</body>
</html>

app/views/layouts/message.js.erb
<%= render partial: "layouts/alert_message", locals:{message: @message, color_class: "success"}%>